version: 2.1
defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/project

commands:
  print_pipeline_id:
    description: "Print pipeline ID"
    parameters:
      id:
        type: string
        default: "ID should br here bro"
    steps:
      - run: 
          name: print pipeline id now
          command: echo <<parameters.id>>
jobs:
  print-great:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - checkout
     - run:
        name: i want to print great
        command: return 1


        

  enr-var-print:
    <<: *defaults
    steps:
      - checkout
      - print_pipeline_id:
          id: ${CIRCLE_WORKFLOW_ID}
      - run:
          name: Print enviroment variable author
          command: |
            echo ${AUTHOR_NAME}

  save_hello_world_output:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create first file
          command: |
            mkdir -p workspace
            echo "MY FIRST FILE IS HERE" > workspace/firstFile.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - firstFile.txt

  print_output_file:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Create first file
          command: |
            cat workspace/firstFile.txt
      
workflows:
  say-hello-workflow:
    jobs:
      - print-great
      - enr-var-print
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
